# Generated by Django 5.2.1 on 2025-05-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaioresDividendos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('dividendo_atual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dividendo_medio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('p_l', models.DecimalField(decimal_places=2, max_digits=6)),
                ('p_vp', models.DecimalField(decimal_places=2, max_digits=6)),
                ('margem_liquida', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_mercado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('setor', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Maior Dividendo',
                'verbose_name_plural': 'Maiores Dividendos',
                'ordering': ['-setor'],
            },
        ),
    ]
