# Generated by Django 5.2.1 on 2025-05-31 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maioresdividendos',
            name='valor_mercado',
        ),
    ]
