# Generated by Django 5.2.1 on 2025-05-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_maioresdividendos_valor_mercado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaioresLucros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('lucro', models.DecimalField(decimal_places=0, max_digits=20)),
                ('p_l', models.DecimalField(decimal_places=2, max_digits=6)),
                ('p_vp', models.DecimalField(decimal_places=2, max_digits=6)),
                ('margem_liquida', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dividendo_medio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('setor', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Maior Lucro',
                'verbose_name_plural': 'Maiores Lucros',
                'ordering': ['-setor'],
            },
        ),
    ]
