# Generated by Django 5.2.1 on 2025-05-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_maioreslucros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maioreslucros',
            name='lucro',
            field=models.CharField(max_length=50),
        ),
    ]
